#!/bin/bash
# uncomment to view debugging information 
set -xeuo pipefail
timedatectl set-ntp true

#check if we're root
if [[ "$UID" -ne 0 ]]; then
    echo "This script needs to be run as root!" >&2
    exit 3
fi

### Config options
locale="en_CA.UTF-8"
hostname=$(date +%Y%b)

### Desktop packages #####
guipacs=(
	lib32-mesa
	xf86-video-amdgpu
	vulkan-radeon
	lib32-vulkan-radeon
	mesa-vdpau
	lib32-mesa-vdpau
	libva-mesa-driver
	lib32-libva-mesa-driver
	smartmontools
	mesa
	vulkan-icd-loader
	lib32-vulkan-icd-loader
    lact
	alsa-utils
	pavucontrol
	pipewire
	pipewire-pulse
	pipewire-alsa
	lib32-pipewire mpv
	conky
	hddtemp
	wget
	nvme-cli
	downgrade
	sysstat
	dunst
	grsync
	htop
	reflector
	pacman-contrib
	linux-headers
	man-db
	ncdu
	btrfs-progs
	kitty
	polkit-gnome
	thunderbird
	hunspell-en_ca
	hyphen-en
	firefox
	libreoffice-fresh
	zathura
	hplip
	cups
	lutris
	steam
	winetricks
	prismlauncher-bin
	jdk8-openjdk
	jdk-openjdk
	heroic-games-launcher-bin
	mcomix
	gthumb
	xnconvert
	calibre
	feh
	noto-fonts-emoji
	ttf-dejavu
	ttf-droid
	ttf-liberation
	ttf-ms-fonts
	qt5-styleplugins
	pcmanfm-gtk3
	file-roller
	gvfs
	unrar
	grim
	geany
	streamlink-twitch-gui-bin
	chatty
	protontricks
	vulkan-intel
	lib32-vulkan-intel
	lib32-gnutls
	lib32-libpulse
	wine-staging
	lib32-giflib
	mpg123
	lib32-mpg123
	lib32-openal
	lib32-v4l-utils
	lib32-libxcomposite
	lib32-libxinerama
	opencl-icd-loader
	lib32-opencl-icd-loader
	lib32-libxslt
	lib32-libva
	lib32-gtk3
	lib32-gst-plugins-base-libs
	cherrytree
	android-file-transfer
	keepassxc
	qbittorrent
	python-pywal
	wpgtk
	virtualbox
	)

# Partition
lsblk
read -p "what drive to install to? " target
echo "Creating partitions..."
#sgdisk -Z /dev/"$target"
sgdisk -d 1 -d 2 /dev/"$target"
sgdisk \
    -n1:0:+512M  -t1:ef00 -c1:boot \
    -N2          -t2:8304 -c2:linux \
    /dev/"$target"
    
# Reload partition table
sleep 2
partprobe -s /dev/"$target"
sleep 2
echo "Encrypting root partition..."

#Encrypt the root partition. prompt for crypt password
cryptsetup luksFormat /dev/disk/by-partlabel/linux
cryptsetup luksOpen /dev/disk/by-partlabel/linux root

echo "Making File Systems..."
# Create file systems
mkfs.fat -F32 -n EFISYSTEM /dev/disk/by-partlabel/boot
mkfs.ext4 -L linux /dev/mapper/root

# mount the root, and create + mount the EFI directory
echo "Mounting File Systems..."
mount /dev/mapper/root /mnt
mkdir /mnt/boot
mount /dev/disk/by-partlabel/boot /mnt/boot

#Update pacman mirrors and then pacstrap base install
echo "Pacstrapping..."
pacstrap -K /mnt base base-devel linux linux-firmware intel-ucode nano cryptsetup git
genfstab -pU /mnt >> /mnt/etc/fstab
#Decrease writes to the USB by using the noatime option in fstab
sed -i 's/relatime/noatime/' /mnt/etc/fstab

echo "Setting up environment..."
arch-chroot /mnt hwclock --systohc --utc
#set up locale/env
#add our locale to locale.gen
sed -i -e "/^#"$locale"/s/^#//" /mnt/etc/locale.gen
arch-chroot /mnt locale-gen
echo LANG=${locale} > /mnt/etc/locale.conf
ln -sf /mnt/usr/share/zoneinfo/America/Vancouver /mnt/etc/localtime
arch-chroot /mnt locale-gen

echo "Configuring for first boot..."
#add the local user
echo -e "[ * ]Adding user"
read -p "Enter your desired username:" user_name
echo "${user_name}:password" | chpasswd -R /mnt

#uncomment the wheel group in the sudoers file
sed -i -e '/^# %wheel ALL=(ALL:ALL) NOPASSWD: ALL/s/^# //' /mnt/etc/sudoers
echo "LANG="$username" ALL=(ALL:ALL) NOPASSWD: /usr/bin/nvme" |sudo tee -a /mnt/etc/sudoers

#change the HOOKS in mkinitcpio.conf
sed -i 's/keymap/keymap encrypt/g' /mnt/etc/mkinitcpio.conf
arch-chroot /mnt mkinitcpio -p linux
 
#enable the services we will need on start up
echo "Enabling services..."
systemctl --root /mnt enable systemd-resolved systemd-networkd
cat <<EOF > /mnt/etc/systemd/network/20-wired.network
	[Match]
	Name=enp8s0
	[Network]
	DHCP=yes
	IPv6PrivacyExtensions=yes
EOF

#Put the following in the /etc/hosts file
echo "127.0.0.1 localhost" >> /mnt/etc/hosts
echo "::1  localhost" >> /mnt/etc/hosts
echo 127.0.1.1 "$hostname".localdomain "$hostname" >> /mnt/etc/hosts

#improve compilation speeds
sed -i "/\[multilib\]/,/Include/"'s/^#//' /mnt/etc/pacman.conf
sed -i 's/-march=[^ ]* -mtune=[^ ]*/-march=native/' /mnt/etc/makepkg.conf
sed -i 's/^#MAKEFLAGS=-j2/MAKEFLAGS=-j$(nproc)/' /mnt/etc/makepkg.conf
sed -i 's/^COMPRESSXZ=(xz -c -z -)/COMPRESSXZ=(xz -c -z - --threads=0)/' /mnt/etc/makepkg.conf

#install the systemd-boot bootloader
arch-chroot /mnt bootctl install
arch-chroot /mnt rm -f /boot/loader/loader.conf
cat <<EOF > /mnt/boot/loader/loader.conf
	default arch
	timeout 3
	editor 0
EOF
cat <<EOF > /mnt/boot/loader/entries/arch.conf
	title arch
	linux /vmlinuz-linux
	initrd /intel-ucode.img
	initrd /initramfs-linux.img
EOF

echo "options cryptdevice=PARTUUID=$(blkid -s PARTUUID -o value /dev/${target}p2):root:allow-discards root=/dev/mapper/root rw quiet split_lock_detect=off loglevel=3 ibt=off" >> /mnt/boot/loader/entries/arch.conf

#install the gui packages
echo "Installing GUI..."
arch-chroot /mnt pacman -Sy --needed "${guipacs[@]}"

#user-specific stuff
arch-chroot -u ${user_name} /mnt bash -s <<-EOF
	HOME=/home/${user_name}
	cd HOME
	
	git clone https://aur.archlinux.org/yay-bin.git
	cd yay-bin
	makepkg -si
	mkdir ~/.dotfiles
	git clone https://gitlab.com/kleshas/dots.git ~/.dotfiles
	
   	sudo pacman -Sc
   	
	read -p "install i3? (y/n)" i3
	if [ "$i3" = "y" ]; then
		yay -S i3-wm i3blocks gnome-screenshot rofi i3lock-fancy-dualmonitors-git xorg-apps lxappearance-gtk3 numlockx xorg-xinit xterm xorg-server redshift-qt pamixer
	fi
	read -p "install sway? (y/n)" sway
	if [ "$sway" = "y" ]; then
		yay -S sway swaytools slurp ydotool evtest otf-font-awesome waybar lxappearance wofi xorg-xwayland xorg-xlsclients qt5-wayland qt6-wayland glfw-wayland gammastep swaylock-effects-git swaybg xdg-desktop-portal-gtk
	fi

	cp -a ~/.dotfiles/.config/. ~/.config
	cp -a ~/.dotfiles/.chatty ~/
	rm ~/.bashrc
	cp ~/.dotfiles/.profile ~/
	cp ~/.dotfiles/.bashrc ~/
	cp ~/.dotfiles/.bash_profile ~/
	cp ~/.dotfiles/.Xresources ~/
	cp ~/.dotfiles/.Xdefaults ~/
	mkdir ~/.scripts
	cp -a ~/.dotfiles/.scripts/. ~/.scripts
	chmod +x ~/.scripts/*.sh
	cd ~/.dotfiles
	stow --adopt -vt ~ .
	git config --global user.email "kleshas@mailbox.org"
	git config --global user.name "kleshas"

	echo "vm.swappiness=10" | sudo tee -a /etc/sysctl.d/99-sysctl.conf

	echo "--protocol https --age 12 --sort rate --latest 5 --save /etc/pacman.d/mirrorlist" |sudo tee /etc/xdg/reflector/reflector.conf
	sudo systemctl enable reflector.service
	sudo systemctl enable fstrim.timer

	wget https://mullvad.net/media/mullvad-code-signing.asc
	gpg2 --import mullvad-code-signing.asc
	gpg2 --edit-key A1198702FC3E0A09A9AE5B75D5A1D4F266DE8DDF
	yay -S mullvad-vpn-bin
	
	sudo bash -c "cat ~/.dotfiles/crypttab > /etc/crypttab"
	sudo bash -c "cat ~/.dotfiles/fstab >> /etc/fstab"
EOF

#lock the root account
#arch-chroot /mnt usermod -L root
#and we're done

echo "-----------------------------------"
echo "- Install complete. Rebooting.... -"
echo "Log in as ${username} and run the apps installer"
echo "-----------------------------------"
sleep 10
sync
reboot

