# --- Main Colors ---
background            #111418
foreground            #e1e2e8
cursor                #e1e2e8
cursor_text_color     #111418

selection_background  #3c4858
selection_foreground  #d7e3f8

url_color             #d7bee4

# --- ANSI Colors ---
color0                #111418
color1                #ffb4ab
color2                #d7bee4
color3                #bbc7db
color4                #a1c9fd
color5                #d7bee4
color6                #bbc7db
color7                #e1e2e8

color8                #43474e
color9                #93000a
color10               #533f5f
color11               #3c4858
color12               #1b4975
color13               #3c4858
color14               #533f5f
color15               #c3c6cf

# --- Starship Prompt Bubbles ---
color255              #1b4975
color254              #a1c9fd
color253              #3c4858
color252              #bbc7db
color251              #533f5f
color250              #d7bee4
color249              #93000a
color248              #ffb4ab

color232              #d2e4ff
color233              #003259
color234              #d7e3f8
color235              #253141
color236              #f3daff
color237              #3b2947
color238              #ffdad6
color239              #690005
color240              #d2e4ff

# Matched with unthemed light/dark
color243              #a1c9fd
color244              #ffb4ab
color245              #43474e

# --- UI Elements ---
active_tab_foreground   #003259
active_tab_background   #a1c9fd
inactive_tab_foreground #d2e4ff
inactive_tab_background #1b4975

active_border_color     #a1c9fd
inactive_border_color   #8d9199

# --- Marks ---
mark1_foreground        #001c37
mark1_background        #d2e4ff
mark2_foreground        #101c2b
mark2_background        #d7e3f8
mark3_foreground        #251431
mark3_background        #f3daff
