#
#  dracula.conf
#
#  Copyright 2022 waxxx333 <waxxx@WindowsXP>
#  Reference the filetypes files before editing this config file.
#
[theme_info]
name=custom
description=A dark theme for many editors, shells, and more.
version=1.0.0
author=Isabelinc
compat=1.22;1.23;1.23.1;1.24

[named_colors]
background=#282a36
current_line=#44475a
selection=#44475a
foreground=#f8f8f2
comment=#6272a4
cyan=#8be9fd
green=#50fa7b
orange=#ffb86c
pink=#ff79c6
purple=#bd93f9
red=#ff5555
yellow=#f1fa8c

[named_styles]
operator=purple
default=foreground;background;false;false
error=red;yellow;false;true
op=purple;background;true;false
# Editor UI
#  selection: words; background
selection=pink;current_line;false;false
current_line=;current_line;true
brace_good=green;comment;true;true
brace_bad=red;comment;true;true
margin_line_number=comment;background
margin_folding=comment;current_line
fold_symbol_highlight=foreground
indent_guide=comment
caret=foreground;;false
marker_line=yellow;yellow
marker_search=background;purple
marker_mark=green;current_line
call_tips=comment;foreground;false;false
white_space=comment;;true

# Basic langs
comment=comment
comment_doc=comment
comment_line=comment
comment_line_doc=comment_doc
comment_doc_keyword=comment,bold
comment_doc_keyword_error=comment,italic

number=cyan
number_1=number
number_2=number_1

# class <color()>
type=pink;;false;true;

class=purple
# def <color():>
function=cyan;;false;true;
parameter=orange


keyword=default
# def, for, in
keyword_1=red;;false;true
keyword_2=default
keyword_3=orange
keyword_4=keyword_2

identifier=cyan;;false;false
# main
identifier_1=foreground;;false;false
identifier_2=default
identifier_3=identifier_2
identifier_4=identifier_2

string=green;;false;false
string_1=orange;;false;false
string_2=green;;false;false
string_3=default
string_4=default
string_eol=string_1
character=string_1
backticks=string_2
here_doc=string_2

scalar=string_2
label=red
preprocessor=green
regex=pink
operator=pink;;true;false
decorator=orange
other=default
extra=keyword;

# Markup
tag=keyword
tag_unknown=tag,bold
tag_end=tag,bold
attribute=type
attribute_unknown=attribute,bold
value=number
entity=number

# Diff
line_added=green
line_removed=red
line_changed=preprocessor
